default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV.fetch("POSTGRES_USERNAME", "postgres") %>
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: njoy_development

test:
  <<: *default
  database: njoy_test

production:
  <<: *default
  database: njoy_production
